services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: samlsample

  web:
    container_name: over
    build: .
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./local.env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db:
